---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../../openshift-gitops
  - external-secrets.yaml
  - namespace-manager-pod-reader-role.yaml
  - namespace-manager-pod-reader-binding.yaml
patches:
  - path: add-hypershift-params.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      name: hypershift-aws-cluster
